### ISSUE TITLE
Wordpressでjqueryを正しく読み込むことができない。

### ISSUE THREAD

**Issue by takuma10Mi** [hikaru08/fiber#19]
jqureyでスライドショーを追加しようとしているが上手くいかない。

WordPressでjQueryが動かない場合の対策と設定方法
https://barikanblog.com/wordpress-can-not-jquery/

あっさり解決！WordPressでjQueryが動かない原因と正しい使い方
https://briarpatch.co.jp/wp-jquery

で試してみたが正しく動作せず。
top-jsのブランチで作業をしています。

使用したいスライドショー
https://techacademy.jp/magazine/9529

**Comment by iwauchi4649** [comment]
確かにjqureyが読み込まれないです。。。下記の記事でも同じ現象が起こっているようです。
https://teratail.com/questions/175498

下記の記事を試してみます。
https://www.momosiri.info/cms/%E3%82%84%E3%81%A3%E3%81%A8%E5%8B%95%E3%81%84%E3%81%9F%EF%BC%81%EF%BC%81wordpress%E3%81%B8%E5%8B%95%E4%BD%9C%E3%81%AE%E8%BB%BD%E3%81%84slick-js%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9F%E3%82%B9%E3%83%A9/

wipファイルプラグインを読み込む方法
https://www.adminweb.jp/wordpress/plugin/index2.html

**Comment by takuma10Mi** [comment]
```
function load_js() {
	//管理画面を除外
	if ( !is_admin() ){
		//事前に読み込まれるjQueryを解除
		wp_deregister_script( 'jquery' );

		//Google CDNのjQueryを出力
		wp_enqueue_script( 'jquery', '//ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js', array(), NULL, true );

		//自作スクリプトや、jQueryのライブラリも同様に読み込みます。
		wp_enqueue_script( 'script-name', get_template_directory_uri() . '/javascript/slide.js', array(), '1.0.0', true );
	}
}
```
をfunction.phpに追加

header.phpで <?php wp_head(); ?>を<head>のはじめに書くと
```
jQuery(function () {
  console.log("動作しました。");
});
```

**Comment by iwauchi4649** [comment]
下記のURLで解決できました。
https://www.willstyle.co.jp/blog/724/
jqureyを使用せずにjsと外部cssのみで実現できました。
<img width="1440" alt="スクリーンショット 2020-07-30 16 25 29" src="https://user-images.githubusercontent.com/54468465/88893752-c8d15e80-d281-11ea-9255-ed00f17787c9.png">

メリット
・導入が簡単
・コード量が少ない

デメリット
・cssがカスタマイズできるかどうか分からない
・自動で画像が切り替わらない（ただし左右のボタンをクリックすると切り替わります）

ご確認の程、よろしくお願いいたします。
